services:
  - type: web
    name: pereschot-vp
    runtime: node
    plan: starter
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
